#!/bin/bash

#mutt_to=~/.muttrc
vimrc_to=~/.vimrc
conkyrc_to=~/.conkyrc
tmux_to=~/.tmux.conf
bashrc_to=~/.bashrc
bash_aliases_to=~/.bash_aliases
gitconfig_to=~/.gitconfig
vim_bundles_to=~/.vim/bundles/bundles.sh

d=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )
#mutt_from=$d/.muttrc
vimrc_from=$d/.vimrc
conkyrc_from=$d/.conkyrc
tmux_from=$d/tmux-config/.tmux.conf
bashrc_from=$d/.bashrc
bash_aliases_from=$d/.bash_aliases
gitconfig_from=$d/.gitconfig
vim_bundles_from=$d/bundles.sh

sync_to() {
	eval to=\$${1}_to
	eval from=\$${1}_from
	ln -s ${from} ${to}
}

sync_from() {
	eval to=\$${1}_to
	eval from=\$${1}_from
	if [[ ! -f ${from} ]]
	then
		cp ${to} ${from}
	fi
}

init_sync_from() {
	# sync_from mutt
	sync_from vimrc
  sync_from conky
	sync_from tmux
	sync_from bashrc
	sync_from bash_aliases
	sync_from gitconfig
	sync_from vim_bundles
}

init_sync_to() {
	# sync_to mutt
	sync_to vimrc
  sync_to_conky
	sync_to tmux
	sync_to bashrc
	sync_to bash_aliases
	sync_to gitconfig
	sync_to vim_bundles
}

# TODO: parse out origin and github urls
get_bundles() {
	
	for d in $(dir)
	do 
		dold=$(pwd)
		cd $d
		git remote -v >> ${dold}/bundles.sh
		cd $dold
	done
}

# init_sync_from
