#!/bin/bash

declare -a dirs
declare -a dist
i=0

for x in ~/java/*/*-[0-9]*
do
	dir=${x%\/*}
	has_dir=0
	j=0
	for d in ${dirs[*]}
	do
		if [[ "$d" == "$dir" ]]; then
			has_dir=1
			echo has dir
			if [[ ${dist[$j]} > $x ]]; then
				echo "${dist[$j]} > $x"
			fi
			if [[ ${dist[$j]} < $x ]]; then
				echo "${dist[$j]} < $x"
				dist[$j]=$x
				echo "${dist[$j]}"
			fi
		fi
		((j++))
	done
	if [[ $has_dir == 0 ]]; then
		dirs[$i]=$dir
		dist[$i]=$x
		((i++))
	fi
done

i=0
for x in ${dirs[*]}
do
	# echo $x
	cdold=$(pwd)
	cd "$x"
	t=${dist[$i]}
	lnk=${t%-*}
	# echo $lnk
	if [[ -L $lnk ]];then
		echo lnk exists
		rm $lnk
	fi
	echo creating symlink $lnk
	ln -s "${dist[$i]}" "$lnk"
	cd "$cdold"
	((i++))
done

